name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  SOLANA_VERSION: 1.18.26
  ANCHOR_VERSION: 0.31.1

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: 'd-skin-swap/yarn.lock'
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache Solana binaries
      uses: actions/cache@v4
      with:
        path: ~/.cache/solana
        key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}
    
    - name: Install Solana
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    
    - name: Install Anchor
      run: |
        cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked
    
    - name: Install dependencies
      working-directory: ./d-skin-swap
      run: yarn install --frozen-lockfile
    
    - name: Build program
      working-directory: ./d-skin-swap
      run: anchor build
    
    - name: Run tests
      working-directory: ./d-skin-swap
      run: anchor test